export const INCREMENT = 'COUNTER/INCREMENT';
export const DECREMENT = 'COUNTER/DECREMENT';
export const INCREMENTBYVALUE = 'COUNTER/INCREMENTBYVALUE';
export const DECREMENTBYVALUE = 'COUNTER/DECREMENTBYVALUE';
