export const ADD_TODO_ITEMS = 'ADD_TODO_ITEMS';
export const DELETE_TODO_ITEMS = 'DELETE_TODO_ITEMS';
export const EDITS_TODO_ITEMS = 'EDITS_TODO_ITEMS';
export const COMPLETE_TODO_ITEMS = 'COMPLETE_TODO_ITEMS';
export const ERROR_TODO_ITEMS = 'ERROR_TODO_ITEMS';
export const LOADING_TODO_ITEMS = 'LOADING_TODO_ITEMS';
