export const GET_MUSIC_REQUEST = 'GET_MUSIC_REQUEST';
export const GET_MUSIC_SUCCESS = 'GET_MUSIC_SUCCESS';
export const GET_MUSIC_FAILURE = 'GET_MUSIC_FAILURE';

export const UPDATE_MUSIC_REQUEST = 'UPDATE_MUSIC_REQUEST';
export const UPDATE_MUSIC_SUCCESS = 'UPDATE_MUSIC_SUCCESS';
export const UPDATE_MUSIC_FAILURE = 'UPDATE_MUSIC_FAILURE';
